// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Monitor struct {
	ID          pgtype.UUID
	Name        string
	Period      int32
	GracePeriod int32
	UserEmail   string
	ProjectID   pgtype.UUID
	PingUrl     string
	Status      pgtype.Text
	Type        pgtype.Text
	LastPing    pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Project struct {
	ID         pgtype.UUID
	Name       string
	Visibility string
	UserEmail  string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type User struct {
	ID        int32
	Name      pgtype.Text
	Email     string
	Password  string
	IsActive  bool
	Otp       pgtype.Text
	LastLogin pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
