services:
  app:
    image: manosriram/outagealert:app
    scale: 2
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
    command: >
      sh -c "doppler run -- ./outagealert"
    tty: true
    ports:
      - "1323"
    depends_on:
      - db
    networks:
      - outagenet
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=outagealert
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - outagenet

  migrations:
    image: ghcr.io/kukymbr/goose-docker
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: none
      replicas: 1
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=db port=5432 user=postgres password=password dbname=outagealert
      - GOOSE_VERBOSE=true
      - GOOSE_COMMAND=up
    volumes:
      - ./migrations:/migrations
    networks:
      - outagenet

networks:
  outagenet:
    name: outagenet
    external: true
    attachable: true

volumes:
  postgres_data:
