services:
  app:
    image: manosriram/outagealert:app
    deploy:
      mode: replicated
      replicas: 2
      update_config:
          parallelism: 2
          delay: 10s
          order: start-first
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
    # restart: always
    networks:
      - public
    command: >
      sh -c "doppler run -- ./outagealert"
    tty: true
    ports:
      - "1323:1323"
    depends_on:
      - db
  
  db:
    image: postgres:13
    deploy:
      mode: replicated
      replicas: 1
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=outagealert
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - public
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 30s

  migrations:
    image: ghcr.io/kukymbr/goose-docker
    depends_on:
      - db
    restart: "no"
    networks:
      - public
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=db port=5432 user=postgres password=password dbname=outagealert
      - GOOSE_VERBOSE=true
      - GOOSE_COMMAND=up
    volumes:
      - ./migrations:/migrations

networks:
  public:
    driver: overlay

volumes:
  postgres_data:
