services:
  app:
    image: manosriram/outagealert:app
    pull_policy: always
    deploy:
      mode: replicated
      replicas: 3
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
    command: >
      sh -c "doppler run -- ./outagealert"
    tty: true
    ports:
      - "1323:1323"
      - "80:1323"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=outagealert
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d outagealert'" ]
      interval: 10s
      timeout: 1s
      retries: 5

  migrations:
    image: ghcr.io/kukymbr/goose-docker
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres port=5432 user=postgres password=password dbname=outagealert
      - GOOSE_VERBOSE=true
      - GOOSE_COMMAND=up
    volumes:
      - ./migrations:/migrations

volumes:
  postgres_data:
  # secondary_volume:
    # driver: local
    # driver_opts:
      # type: none
      # device: /mnt/volume_sgp1_02
      # o: bind
