version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/golang:1.23
    working_directory: ~/app

jobs:
  deploy:
    executor: docker-executor
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:rN+i8mdjL+3yd3icI7KqeRE6OTOGm6VA++T3Mi9cyjY"
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Setup and Deploy
          command: |
            chmod +x ./deploy.sh
            ./deploy.sh

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
