version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:CtV/KHY1P7Ecte5xdGXNcESyGeeVCBSp4XIc6ZvFXr4"
      - checkout
      - run:
          name: Setup
          command: |
            ssh-keyscan $OUTAGEALERT_IP >> ~/.ssh/known_hosts
      - run:
          name: Deploy to VM
          command: ssh -v root@$OUTAGEALERT_IP "yes | docker system prune && cd /root/dev/outagealert.io && git pull origin main && docker-compose down && docker-compose up -d --build && exit"

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
