version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d4:1b:e9:0d:80:77:61:01:4d:05:be:6c:96:eb:bb:71"
            - "SHA256:CtV/KHY1P7Ecte5xdGXNcESyGeeVCBSp4XIc6ZvFXr4"
      - run:
          name: Setup
          command: |
            chmod 755 .circleci/deploy.sh
            ssh-keyscan 157.230.242.217 >> ~/.ssh/known_hosts
      - run:
          name: Deploy to VM
          command: .circleci/deploy.sh

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
