version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d4:1b:e9:0d:80:77:61:01:4d:05:be:6c:96:eb:bb:71"

      - run:
          name: Add VM to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H 157.230.242.217 >> ~/.ssh/known_hosts
      - run:
          name: Deploy to VM
          command: |
            ssh root@157.230.242.217 \
              cd /dev/outagealert \
              git pull origin main \
              docker-compose pull \
              docker-compose up -d --remove-orphans --no-deps \
              docker image prune -f

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
