version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/golang:1.23
    working_directory: ~/app

jobs:
  deploy:
    executor: docker-executor
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:CtV/KHY1P7Ecte5xdGXNcESyGeeVCBSp4XIc6ZvFXr4"
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Setup
          command: |
            ssh-keyscan $OUTAGEALERT_IP >> ~/.ssh/known_hosts
            echo $DOCKER_REGISTRY_PAT | docker login -u manosriram --password-stdin
            docker-compose build
            docker-compose push
      - run:
          name: Deploy to VM
          command: ssh -v root@$OUTAGEALERT_IP "yes | docker system prune && cd /root/dev/outagealert.io && git pull origin main && curl -Ls https://cli.doppler.com/install.sh | sh && doppler configure set token $DOPPLER_TOKEN && docker-compose pull && docker-compose up -d"

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
